CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "google_sub" varchar(255) UNIQUE NOT NULL,
  "name" varchar(64) NOT NULL,
  "avatar_url" varchar(1024),
  "role_id" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(64) UNIQUE NOT NULL
);

CREATE TABLE "games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url_id" VARCHAR(32) UNIQUE NOT NULL DEFAULT (translate(gen_random_uuid()::text, '-', '')::varchar(32)),
  "status_id" INT NOT NULL,
  "started_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "game_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(64) NOT NULL
);

CREATE TABLE "chains" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int NOT NULL
);

CREATE TABLE "prompts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chain_id" int NOT NULL,
  "index" int NOT NULL,
  "text" varchar(256) NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "s3_url" varchar(1024) NOT NULL,
  "prompt_id" int UNIQUE NOT NULL,
  "user_id" int NOT NULL
);

COMMENT ON COLUMN games.status_id IS '"pending", "active", "completed", "abandoned"';

COMMENT ON COLUMN prompts.index IS '0-based turn index';

COMMENT ON COLUMN prompts.text IS '≤ 256 chars';

COMMENT ON COLUMN images.s3_url IS 'S3 link to PNG/JPEG';

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "chains" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "prompts" ADD FOREIGN KEY ("chain_id") REFERENCES "chains" ("id");

ALTER TABLE "prompts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "prompts" ADD CONSTRAINT "unique_game_index" UNIQUE ("chain_id", "index");

ALTER TABLE "images" ADD FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id");

ALTER TABLE "images" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "games" ADD FOREIGN KEY ("status_id") REFERENCES "game_statuses" ("id");
