version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - DB_HOST=${RDS_ENDPOINT}
      - DB_USER=${RDS_DB_NAME}
      - DB_NAME=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules