name: Build Docker Image

on:
  workflow_run:
    workflows: ["Infrastructure Provisioning"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        push: false
        build-args: |
          RDS_ENDPOINT=${{ needs.terraform.outputs.RDS_ENDPOINT }}
          RDS_DB_NAME=${{ needs.terraform.outputs.RDS_DB_NAME }}
          RDS_USERNAME=${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}