name: Flyway Database Migrations

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - '.github/workflows/flyway-migrations.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Flyway
        run: |
          wget -q -O flyway-commandline.zip https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3.zip
          unzip flyway-commandline.zip -d flyway
          rm flyway-commandline.zip
          echo "$(pwd)/flyway" >> $GITHUB_PATH

      - name: Get Terraform outputs
        id: terraform
        run: |
          echo "DB_HOST=$(terraform output -raw db_host)" >> $GITHUB_OUTPUT
          echo "DB_NAME=$(terraform output -raw db_name)" >> $GITHUB_OUTPUT

      - name: Run Flyway migrations
        env:
          FLYWAY_URL: jdbc:postgresql://${{ steps.terraform.outputs.DB_HOST }}:5432/${{ steps.terraform.outputs.DB_NAME }}
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          flyway migrate