name: Infrastructure Provisioning

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -var "db_username=${{ secrets.TF_VAR_DB_USERNAME }}" -var "db_password=${{ secrets.TF_VAR_DB_PASSWORD }}"
      working-directory: ./terraform
      
    - name: Get Terraform Outputs
      id: terraform
      run: |
        echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT
        echo "RDS_DB_NAME=$(terraform output -raw rds_db_name)" >> $GITHUB_OUTPUT
      working-directory: ./terraform